import { NextRequest, NextResponse } from "next/server";
import {
  MercadoPagoConfig,
  PreApproval,
  Customer,
  CardToken,
} from "mercadopago";

// Initialize Mercado Pago
import { adminDb } from "@/lib/firebase-admin";

const client = new MercadoPagoConfig({
  accessToken: process.env.MP_ACCESS_TOKEN!,
});

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { formData, payer_email, plan, uid } = body;

    if (!payer_email) {
      return NextResponse.json(
        { error: "Email do pagador é obrigatório" },
        { status: 400 },
      );
    }

    console.log("Processing payment for:", payer_email, "Plan:", plan);
    console.log("Token received:", formData?.token ? "Yes" : "No");

    // 1. Create Customer (or find existing - simplified here, ideally we store customer_id in user profile)
    // For now, simpler approach: Use the token to create a subscription directly if possible.
    // However, for recurring payments, it's best practice to associate card with customer.

    const customerClient = new Customer(client);

    // Check if we can just use the token to create Subscription (PreApproval)
    // The PreApproval API takes 'card_token_id'.

    const preapproval = new PreApproval(client);

    const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:3000";
    // Ensure valid protocol and no double slashes
    let safeBaseUrl = baseUrl;
    if (!safeBaseUrl.startsWith("http")) {
      safeBaseUrl = `https://${safeBaseUrl}`;
    }
    const backUrl = new URL("/dashboard", safeBaseUrl);
    backUrl.searchParams.set("payment", "success");

    const subscriptionData = {
      body: {
        reason: "EduCreator AI - Assinatura",
        auto_recurring: {
          frequency: 1,
          frequency_type: "months",
          transaction_amount: 21.9,
          currency_id: "BRL",
        } as any,
        back_url: backUrl.toString(),
        payer_email: payer_email,
        card_token_id: formData.token, // Use the token generated by the frontend Brick
        status: "authorized", // Attempt to authorize immediately
        external_reference: uid,
      },
    };

    if (plan === "trial") {
      // Add free trial
      (subscriptionData.body.auto_recurring as any).free_trial = {
        frequency: 7,
        frequency_type: "days",
      };
    }

    // Create Subscription
    const response = await preapproval.create(subscriptionData);

    console.log("Subscription created:", response.id);

    // Update User in Firestore
    if (adminDb && uid) {
      try {
        await adminDb
          .collection("users")
          .doc(uid)
          .set(
            {
              plan: plan,
              status: "active",
              subscriptionId: response.id,
              updatedAt: new Date().toISOString(),
              isTrial: plan === "trial",
              trialStartDate:
                plan === "trial" ? new Date().toISOString() : null,
              trialEndDate:
                plan === "trial"
                  ? new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString()
                  : null,
            },
            { merge: true },
          );
        console.log("✅ User updated in Firestore:", uid);
      } catch (dbError) {
        console.error("❌ Error updating user in Firestore:", dbError);
      }
    } else {
      console.warn(
        "⚠️ Firestore Admin DB not initialized or UID missing. User not updated.",
      );
    }

    // Send Welcome Email
    try {
      // Dynamic import to avoid circular dependency issues if any, though likely not needed here.
      // Better to use the imported function.
      const { sendWelcomeEmail } = await import("@/lib/email");
      await sendWelcomeEmail(payer_email, plan, plan === "trial");
    } catch (emailError) {
      console.error("❌ Error initiating email send:", emailError);
    }

    return NextResponse.json(response);
  } catch (error) {
    console.error("Payment Processing Error:", error);
    return NextResponse.json(
      { error: "Erro ao processar pagamento", details: error },
      { status: 500 },
    );
  }
}
